### ISSUE TITLE
TypeError: Cannot access member 'split' of undefined at chanChange (animatedChannel.js:186:76)

### ISSUE THREAD

**Issue by dodancs** [xDefcon/sinusbot-scripts#29]
Hey.

This is an issue that I'm facing. The script seems to work okay, but the server console is spammed with this message. Also the CPU usage is quite high.

This is the message:
`WARN Error in script (event: setInterval callback): TypeError: Cannot access member 'split' of undefined
at chanChange (animatedChannel.js:186:76)`

Hopefully you can address this issue.
Thank you.

**Comment by xDefcon** [comment]
Sorry for huge delay, the problem is that the script needs a recode, it works only if you set the same amount of animated descriptions and channels (same comma separated value amount).
